# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build_exe:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies (without dev)
      run: uv sync --locked --no-dev

    - name: Lint with ruff
      uses: astral-sh/ruff-action@v3

    - name: build exe
      run: |
        # call pyinstaller 
        uv run pyinstaller times.spec

    - name: zip output
      run:
        python -c "import shutil; shutil.make_archive('distFolder', 'zip', 'dist/times')"

    - name: archive zipfile
      uses: actions/upload-artifact@v6
      with:
        name: distFolder
        path: distFolder.zip
        retention-days: 3
